version: "3.3"
services:
  bot:
    build:
      context: .
      dockerfile: dev-Dockerfile
    volumes:
      # host:container
      - "/mnt/c/Users/flyer/Documents/dockers/nhl-helper/db:/usr/src/app/data"
      - "/mnt/c/Users/flyer/Documents/GitHub/NHL-Helper-Bot/dist:/usr/src/app/src"
