version: "3.3"
services:
  configGenerator:
    build:
      context: ../..
      dockerfile: scripts/configGen/Dockerfile
    volumes:
      - ./src/common/config:/config
    environment:
      - ENVIRONMENT=docker
