export default {
  productionMode: false,
  production: {
    token: "",
    logLevel: 3,
    masterGuildId: "",
    prefix: {
      normal: "",
      admin: "",
    },
    customCommandListChannelId: "",
    imageKit: {
      publicKey: "",
      privateKey: "",
      urlEndpoint: "",
      redirectUrl: "",
      proxyUrl: "",
    },
    imgur: {
      clientId: "",
      clientSecret: "",
    },
    reactionRoles: {
      channelId: "",
      reactionRoles: [],
    },
    vistorReactRole: {
      memberRoleId: "",
      visitorRoleId: "",
      visitorEmojiId: "",
      rolesChannelId: "",
    },
    gameDayPosts: {
      channelId: "",
      tagIds: {
        preseason: "",
        regularSeason: "",
        postseason: "",
        seasons: [],
      },
    },
    joinLeaveMessageChannelId: "",
    userLogChannelId: "",
    voiceStatsChannels: [],
    commandTempChannelId: "",
    bluesky: {
      username: "",
      password: "",
      listId: "",
      channelId: "",
    },
    pinsChannelId: "",
  },
  nonProduction: {
    token: "",
    logLevel: 3,
    masterGuildId: "",
    prefix: {
      normal: "",
      admin: "",
    },
    customCommandListChannelId: "",
    imageKit: {
      publicKey: "",
      privateKey: "",
      urlEndpoint: "",
      redirectUrl: "",
      proxyUrl: "",
    },
    imgur: {
      clientId: "",
      clientSecret: "",
    },
    reactionRoles: {
      channelId: "",
      reactionRoles: [],
    },
    vistorReactRole: {
      memberRoleId: "",
      visitorRoleId: "",
      visitorEmojiId: "",
      rolesChannelId: "",
    },
    gameDayPosts: {
      channelId: "",
      tagIds: {
        preseason: "",
        regularSeason: "",
        postseason: "",
        seasons: [],
      },
    },
    joinLeaveMessageChannelId: "",
    userLogChannelId: "",
    voiceStatsChannels: [],
    commandTempChannelId: "",
    bluesky: {
      username: "",
      password: "",
      listId: "",
      channelId: "",
    },
    pinsChannelId: "",
  },
};
